version: 2.1

commands:
  destroy-environment:
    description: Destroy s3 bucket and cloudformation
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name StaticWebsite
            aws s3 rm s3://travel-blog-ke/ --recursive
            aws s3api delete-bucket --bucket travel-blog-ke --region us-east-1

jobs:
  create-bucket:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create S3 Bucket
          command: |
            aws s3api create-bucket --bucket travel-blog-ke --region us-east-1

  upload-files:
    docker:
      - image: python:3.9.0-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update curl rsync openssh
            pip install awscli
      - run:
          name: Copy file to s3
          command: |
            aws s3api list-buckets
            cd website
            aws s3api put-object --bucket travel-blog-ke --key index.html --body index.html
            aws s3api put-object --bucket travel-blog-ke --key index.js --body index.js
            aws s3 cp css/ s3://travel-blog-ke/css/ --recursive 
            aws s3 cp img/ s3://travel-blog-ke/img/ --recursive
      - destroy-environment

  configure-bucket:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Add IAM and turn on static website hosting
          command: |
            aws s3api put-bucket-policy --bucket travel-blog-ke --policy file://policy.json
            aws s3 website s3://travel-blog-ke/ --index-document index.html
      - destroy-environment

  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create cloudfront and configure it to use s3 bucket.
          command: |
            aws cloudformation deploy \
            --template-file .circleci/files/cloudfront.yml \
            --tags project=travelblog \
            --stack-name StaticWebsite
      - destroy-environment

workflows:
  default:
    jobs:
      - create-bucket
      - upload-files:
          requires: [create-bucket]
      - configure-bucket:
          requires: [upload-files]
      - deploy:
          requires: [configure-bucket]
